=== ttab/elephant-repository/revisor/constraints/spec.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "schema://elephant/doc/spec",
  "title": "Elephant document spec format",
  "type":"object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "version": {
      "type": "integer",
      "const": 1
    },
    "name": {
      "type": "string"
    },
    "documents": {
      "type": "array",
      "items": { "$ref": "#/definitions/document" }
    },
    "meta": {
      "type": "array",
      "items": { "$ref": "#/definitions/block" }
    },
    "links": {
      "type": "array",
      "items": { "$ref": "#/definitions/block" }
    },
    "content": {
      "type": "array",
      "items": { "$ref": "#/definitions/block" }
    },
    "htmlPolicies": {
      "type": "array",
      "items": { "$ref": "#/definitions/htmlPolicy" }
    },
    "attributes": { "$ref": "#/definitions/docAttrConstraints" }
  },
  "additionalProperties": false,
  "required": ["version", "name"],
  "definitions": {
    "document": {
      "type": "object",
      "properties": {
        "name": {"type":"string"},
        "description": {"type":"string"},
        "declares": {"type":"string"},
        "meta": {
          "type": "array",
          "items": { "$ref": "#/definitions/block" }
        },
        "links": {
          "type": "array",
          "items": { "$ref": "#/definitions/block" }
        },
        "content": {
          "type": "array",
          "items": { "$ref": "#/definitions/block" }
        },
        "properties": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": { "$ref": "#/definitions/property" }
        }
      }
    },
    "htmlPolicy": {
      "type": "object",
      "properties": {
        "name": {"type":"string"},
        "description": {"type":"string"},
        "elements": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {
            "type": "object",
            "properties": {
              "attributes": { "$ref": "#/definitions/stringConstraintMap" }
            }
          }
        }
      }
    },
    "block": {
      "type": "object",
      "properties": {
        "name": {"type":"string"},
        "description": {"type":"string"},
        "count": {"type":"integer"},
        "maxCount": {"type":"integer"},
        "minCount": {"type":"integer"},
        "declares": { "$ref": "#/definitions/blockDeclaration" },
        "match": { "$ref": "#/definitions/blockMatchConstraints" },
        "attributes": { "$ref": "#/definitions/blockAttrConstraints" },
        "data": { "$ref": "#/definitions/stringConstraintMap" },
        "meta": {
          "type": "array",
          "items": { "$ref": "#/definitions/block" }
        },
        "links": {
          "type": "array",
          "items": { "$ref": "#/definitions/block" }
        },
        "content": {
          "type": "array",
          "items": { "$ref": "#/definitions/block" }
        },
        "blocksFrom": {
          "type": "array",
          "items": { "$ref": "#/definitions/blocksFrom" }
        }
      },
      "additionalProperties": false
    },
    "blocksFrom": {
      "type": "object",
      "properties": {
        "docType": {"type":"string"},
        "global": {"type":"boolean"},
        "kind": {
          "type":"string",
          "enum": ["link", "meta", "content"]
        }
      },
      "additionalProperties": false
    },
    "docAttrConstraints": {
      "propertyNames": {
        "type": "string",
        "enum": [
          "uuid", "type", "language", "status", "uri", "url", "title",
          "provider", "subtype", "path"
        ]
      },
      "additionalProperties": { "$ref": "#/definitions/stringConstraint" }
    },
    "docMatchConstraints": {
      "propertyNames": {
        "type": "string",
        "enum": [
          "type", "subtype", "provider"
        ]
      },
      "additionalProperties": { "$ref": "#/definitions/stringConstraint" }
    },
    "blockDeclaration": {
      "type": "object",
      "properties": {
        "type": {"type":"string"},
        "rel": {"type":"string"}
      },
      "anyOf": [
        {"required": ["type"]},
        {"required": ["rel"]}
      ],
      "additionalProperties": false
    },
    "blockAttrConstraints": {
      "propertyNames": {
        "type": "string",
        "enum": [
          "uuid", "type", "uri", "url", "title", "rel",
          "name", "value", "contenttype", "role"
        ]
      },
      "additionalProperties": { "$ref": "#/definitions/stringConstraint" }
    },
    "blockMatchConstraints": {
      "propertyNames": {
        "type": "string",
        "enum": [
          "type", "uri", "url", "rel",
          "name", "value", "contenttype", "role"
        ]
      },
      "additionalProperties": { "$ref": "#/definitions/stringConstraint" }
    },
    "stringConstraintMap": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": { "$ref": "#/definitions/stringConstraint" }
    },
    "stringConstraint": {
      "type": "object",
      "properties": {
        "name": {"type":"string"},
        "description": {"type":"string"},
        "optional": {"type":"boolean"},
        "allowEmpty": {"type":"boolean"},
        "const": {"type":"string"},
        "enum": {
          "type": "array",
          "items": {"type":"string"}
        },
        "pattern": {"type":"string"},
        "glob": {
          "type": "array",
          "items": {"type":"string"}
        },
        "template": {"type":"string"},
        "format": {
          "format": "string",
          "enum": ["RFC3339", "int", "float", "bool", "html"]
        },
        "time": {"type":"string"},
        "htmlPolicy": {"type":"string"}
      }
    }
  }
}

=== ttab/elephant-repository/revisor/constraints/core.json
{
  "version": 1,
  "name": "Core",
  "meta": [
    {
      "declares": {"type":"core/note"},
      "attributes": {
        "role": {"enum": ["public", "internal"]}
      },
      "data": {
        "text": {"allowEmpty":true}
      }
    },
    {
      "name": "Description",
      "description": "A public or internal description of the entity",
      "declares": {"type":"core/description"},
      "attributes": {
        "role": {"enum":["public", "internal"]}
      },
      "data": {
        "text": {"allowEmpty":true}
      }
    },
    {
      "declares": {"type":"core/definition"},
      "attributes": {
        "role": {"enum": ["short", "long"]}
      },
      "data": {
        "text": {"allowEmpty":true}
      }
    }
  ],
  "documents": [
    {
      "name": "Place",
      "description": "A geographical location",
      "declares": "core/place",
      "meta": [
        {
          "declares": {"type":"core/position"},
          "data": {
            "geometry": {
              "description": "TODO: add a WKT format?"
            }
          }
        }
      ]
    },
    {
      "name": "Section",
      "description": "An section for content",
      "declares": "core/section"
    },
    {
      "name": "Topic",
      "description": "An topic for content",
      "declares": "core/topic"
    },
    {
      "name": "Story",
      "description": "An ongoing story that gets reported on",
      "declares": "core/story"
    },
    {
      "name": "Person",
      "description": "Used to describe people",
      "declares": "core/person",
      "meta": [
        {
          "declares": {"type":"core/contact-info"},
          "data": {}
        }
      ]
    },
    {
      "name": "Author",
      "description": "An author document used for f.ex. bylines",
      "declares": "core/author",
      "meta": [
        {
          "declares": {"type":"core/contact-info"},
          "data": {
            "email": {"optional":true},
            "name": {"optional":true},
            "firstName": {"optional":true},
            "lastName": {"optional":true},
            "mobile": {"optional":true},
            "phone": {"optional":true},
            "postalCode": {
              "description": "TODO: only in 83d072c8-fb07-47e2-9c5b-85f4453835f6?",
              "optional": true
            },
            "streetAddress": {
              "description": "TODO: only in 83d072c8-fb07-47e2-9c5b-85f4453835f6?",
              "optional": true
            },
            "city": {
              "description": "TODO: only in 83d072c8-fb07-47e2-9c5b-85f4453835f6?",
              "optional": true
            },
            "country": {
              "description": "TODO: only in 83d072c8-fb07-47e2-9c5b-85f4453835f6?",
              "optional": true
            }
          }
        }
      ],
      "links": [
        {
          "name": "Association with NavigaID user account",
          "declares": {"type":"x-imid/user", "rel":"same-as"},
          "attributes": {
            "uri": {"glob":["imid://user/sub/*"]}
          }
        }
      ]
    },
    {
      "name": "Category",
      "description": "A category for content",
      "declares": "core/category",
      "links": [
        {
          "declares": {"rel":"broader"},
          "attributes": {
            "type": {},
            "uuid": {"optional":true},
            "uri": {"optional":true}
          }
        }
      ]
    },
    {
      "name": "Channel",
      "description": "A publication channel",
      "declares": "core/channel"
    },
    {
      "name": "Article",
      "description": "An editorial article",
      "declares": "core/article",
      "content": [
        {
          "declares": {"type":"core/heading-1"},
          "data": {
            "text":{
              "allowEmpty":true,
              "format": "html"
            }
          }
        },
        {
          "declares": {"type":"core/heading-2"},
          "data": {
            "text":{
              "allowEmpty":true,
              "format": "html"
            }
          }
        },
        {
          "declares": {"type":"core/heading-3"},
          "data": {
            "text":{
              "allowEmpty":true,
              "format": "html"
            }
          }
        },
        {
          "declares": {"type":"core/heading-4"},
          "data": {
            "text":{
              "allowEmpty":true,
              "format": "html"
            }
          }
        },
        {
          "declares": {"type":"core/paragraph"},
          "data": {
            "text":{
              "allowEmpty":true,
              "format": "html"
            }
          }
        },
        {
          "declares": {"type":"core/preamble"},
          "data": {
            "text":{
              "allowEmpty":true,
              "format": "html"
            }
          }
        },
        {
          "name": "Core image block",
          "declares": {"type":"core/image"},
          "attributes": {
            "uuid":{}
          },
          "links": [
            {
              "declares": {"rel":"self", "type":"core/image"},
              "attributes": {
                "uuid": {},
                "uri": {"glob":["core://image/*"]}
              },
              "data": {
                "height": {"format":"int"},
                "width": {"format":"int"},
                "alttext": {
                  "optional": true,
                  "allowEmpty": true
                },
                "text": {
                  "optional": true,
                  "allowEmpty": true
                }
              },
              "links": [
                {
                  "declares": {"rel":"author", "type":"core/author"},
                  "attributes": {
                    "title": {},
                    "uuid": {}
                  }
                }
              ]
            }
          ]
        },
        {
          "declares": {"type":"core/youtube"},
          "attributes": {
            "uri": {"glob":["https://www.youtube.com/**"]},
            "url": {"glob":["https://www.youtube.com/**"]}
          },
          "data": {
            "start": {"format":"int"}
          },
          "links": [
            {
              "declares": {"rel":"alternate", "type": "text/html"},
              "attributes": {
                "url": {"glob":["https://www.youtube.com/**"]},
                "title": {}
              }
            },
            {
              "declares": {"rel":"alternate", "type":"image/jpg"},
              "attributes": {
                "url":{}
              },
              "data": {
                "height": {"format":"int"},
                "width": {"format":"int"}
              }
            }
          ]
        },
        {
          "declares": {"type":"core/blockquote"},
          "data": {
            "text":{
              "allowEmpty":true,
              "format": "html"
            }
          }
        },
        {
          "declares": {"type":"core/htmlembed"},
          "data": {
            "text":{
              "description": "TODO: add 'anything goes' policy to revisor to be able to use the html format validation for free-form html",
              "allowEmpty":true
            }
          }
        },
        {
          "declares": {"type":"core/unordered-list"},
          "content": [
            {
              "declares": {"type":"core/paragraph"},
              "data": {
                "text":{
                  "allowEmpty":true,
                  "format": "html"
                }
              }
            }
          ]
        },
        {
          "declares": {"type":"core/ordered-list"},
          "content": [
            {
              "declares": {"type":"core/paragraph"},
              "data": {
                "text":{
                  "allowEmpty":true,
                  "format": "html"
                }
              }
            }
          ]
        },
        {
          "declares": {"type":"core/factbox"},
          "attributes": {
            "title": {}
          },
          "data": {
            "byline": {}
          },
          "blocksFrom":[
            {"docType":"core/article", "kind": "content", "global":true}
          ]
        },
        {
          "name": "Table",
          "declares": {"type":"core/table"},
          "data": {
            "caption": {"allowEmpty":true, "optional":true},
            "meta": {"allowEmpty":true},
            "thead": {
              "format": "html",
              "htmlPolicy": "table",
              "optional": true
            },
            "tbody": {
              "format": "html",
              "htmlPolicy": "table"
            },
            "tfoot": {
              "format": "html",
              "htmlPolicy": "table",
              "optional": true
            }
          }
        },
        {
          "name": "Social embed",
          "declares": {"type":"core/socialembed"},
          "links": [
            {
              "name": "Twitter embed link",
              "declares": {"type":"core/tweet", "rel":"self"},
              "attributes": {
                "uri": {"glob":["core://tweet/*"]},
                "url": {"glob":["https://twitter.com/**"]}
              }
            },
            {
              "name": "Instagram embed link",
              "declares": {"type":"core/instagram", "rel":"self"},
              "attributes": {
                "uri": {"glob":["core://instagram/*"]},
                "url": {"glob":["https://www.instagram.com/**"]}
              }
            },
            {
              "name": "Embed location link",
              "declares": {"type":"text/html", "rel":"alternate"},
              "attributes": {
                "title": {},
                "url": {}
              },
              "data": {
                "context": {},
                "provider": {}
              }
            },
            {
              "name": "Embed image",
